[pytest]
minversion = 7.0
addopts = -ra
pythonpath = backend_python
testpaths =
    backend_python/app/tests
    backend_python/tests
markers =
    clean_db: reset and clean database state before test
filterwarnings =
    ignore::DeprecationWarning:passlib.*
    ignore::DeprecationWarning:argon2.*
