[pytest]
minversion = 7.0
addopts = -ra
testpaths =
    backend_python/app/tests
markers =
    clean_db: reset and clean database state before test
filterwarnings =
    ignore::DeprecationWarning:passlib.*
    ignore::DeprecationWarning:argon2.*
