import asyncio
import json
import time
from fastapi import APIRouter, HTTPException, Depends, Header
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional, List, Dict, Any

from app.schemas import ChatRequest, ChatResponse
from app.core.tenant import TenantContext, get_tenant_context
from app.services.agent_runtime import AgentRuntime
from app.services.usage_service import UsageService
from app.services.rate_limiter import RateLimiter
from app.db.database import db

router = APIRouter(prefix="/chat", tags=["Agent Chat & Streaming"])

@router.post("", response_model=ChatResponse)
@router.post("/message", response_model=ChatResponse)
async def process_chat_message(
    req: ChatRequest,
    ctx: TenantContext = Depends(get_tenant_context)
):
    """
    Direct synchronous AI agent execution with RAG retrieval, anti-spam rate limiting, and tool gates.
    """
    # 0. Global AI Killswitch Interception
    if db.global_killswitch_active:
        raise HTTPException(
            status_code=503,
            detail=f"Global AI operations are currently paused by platform administration. Reason: {db.global_killswitch_reason or 'Emergency Maintenance'}"
        )

    company_id = ctx.company_id
    
    # 1. Anti-spam & Cost Protection: Max 20 requests/minute per tenant session
    client_key = f"{company_id}_{req.conversation_id or req.session_id or 'anon'}"
    RateLimiter.check_rate_limit(client_key, max_requests=20)

    stored_chunks = db.get_document_chunks_for_tenant(company_id, only_active=True)
    agent = db.get_agent_for_company(company_id) or {"name": "Coar AI", "model": "gpt-4o-mini"}

    response = await AgentRuntime.process_message(
        request=req,
        company_id=company_id,
        agent_config=agent,
        stored_chunks=stored_chunks
    )

    # Record usage
    UsageService.record_event(company_id, "message", 1, "messages", req.conversation_id or req.session_id)
    UsageService.record_event(company_id, "llm_tokens", response.tokens_used, "tokens", req.conversation_id or req.session_id)

    return response

@router.post("/stream")
async def stream_chat_tokens(
    req: ChatRequest,
    ctx: TenantContext = Depends(get_tenant_context)
):
    """
    Real SSE Token Streaming endpoint for React chat widgets and web dashboards.
    Streams tokens directly as they are generated by the LLM provider.
    """
    # 0. Global AI Killswitch Interception
    if db.global_killswitch_active:
        raise HTTPException(
            status_code=503,
            detail=f"Global AI operations are currently paused by platform administration. Reason: {db.global_killswitch_reason or 'Emergency Maintenance'}"
        )

    company_id = ctx.company_id
    
    # 1. Anti-spam & Cost Protection: Max 20 requests/minute per tenant session
    client_key = f"{company_id}_{req.conversation_id or req.session_id or 'anon'}"
    RateLimiter.check_rate_limit(client_key, max_requests=20)

    stored_chunks = db.get_document_chunks_for_tenant(company_id, only_active=True)
    agent = db.get_agent_for_company(company_id) or {"name": "Coar AI", "model": "gpt-4o-mini"}

    return StreamingResponse(
        AgentRuntime.stream_process_message(
            request=req,
            company_id=company_id,
            agent_config=agent,
            stored_chunks=stored_chunks
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )
