import asyncio
import json
import logging
import httpx
import re
from typing import AsyncGenerator, Dict, List, Optional, Tuple
from app.core.config import settings

logger = logging.getLogger(__name__)

class LLMProvider:
    """
    Multi-Provider & Custom In-House Model API Service.
    Supports:
    - Custom In-House Product API (via CUSTOM_LLM_API_URL / Sarvam AI)
    - Self-Hosted Ollama / vLLM / LocalAI
    - Built-in grounded RAG synthesis engine fallback
    """

    @classmethod
    def count_tokens(cls, text: str, model: str = "gpt-4o") -> int:
        """Accurately calculates real token counts using tiktoken with deterministic fallback."""
        if not text:
            return 0
        try:
            import tiktoken
            try:
                enc = tiktoken.encoding_for_model(model)
            except Exception:
                enc = tiktoken.get_encoding("cl100k_base")
            return len(enc.encode(text))
        except Exception:
            return max(1, (len(text) + 3) // 4)

    @classmethod
    async def generate_response_with_mode(
        cls,
        prompt: str,
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: float = 0.3,
        max_tokens: int = 1000
    ) -> Tuple[str, str]:
        """
        Generates a model response and returns (response_text, generation_mode).
        generation_mode is 'llm' when generated by the neural model, or 'template_fallback' on error/offline.
        """
        target_model = model or settings.DEFAULT_LLM_MODEL
        custom_url = settings.CUSTOM_LLM_API_URL

        # 1. Dispatch to Custom In-House Product / Sarvam API if configured with API key
        if custom_url and settings.CUSTOM_LLM_API_KEY:
            try:
                headers = {"Content-Type": "application/json"}
                headers["Authorization"] = f"Bearer {settings.CUSTOM_LLM_API_KEY}"
                headers["api-subscription-key"] = settings.CUSTOM_LLM_API_KEY

                payload = {
                    "model": target_model,
                    "messages": [
                        *([{"role": "system", "content": system_instruction}] if system_instruction else []),
                        {"role": "user", "content": prompt}
                    ],
                    "temperature": temperature,
                    "max_tokens": max_tokens
                }

                async with httpx.AsyncClient(timeout=30.0) as client:
                    resp = await client.post(custom_url, headers=headers, json=payload)
                    if resp.status_code == 200:
                        data = resp.json()
                        # Extract response from standard choices or custom response key
                        if "choices" in data and len(data["choices"]) > 0:
                            content = data["choices"][0].get("message", {}).get("content", "")
                            if content:
                                return content.strip(), "llm"
                        elif "response" in data and data["response"]:
                            return str(data["response"]).strip(), "llm"
                        elif "message" in data and data["message"]:
                            return str(data["message"]).strip(), "llm"
                    else:
                        logger.error(f"[LLM API Error] Upstream {custom_url} returned HTTP {resp.status_code}: {resp.text}")
            except Exception as e:
                logger.error(f"[LLM API Exception] Failed to call LLM provider: {type(e).__name__} - {e}")

        # 2. Local Grounded Extraction (when external API is not configured or offline)
        if system_instruction and "Verified Knowledge Context:" in system_instruction:
            fallback_text = cls.synthesize_grounded_answer(prompt, system_instruction)
            return fallback_text, "template_fallback"

        return f"Regarding your inquiry about '{prompt}', our team is available to assist.", "template_fallback"

    @classmethod
    async def generate_response(
        cls,
        prompt: str,
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: float = 0.3,
        max_tokens: int = 1000
    ) -> str:
        """Backward-compatible response generation returning response text."""
        text, _ = await cls.generate_response_with_mode(
            prompt=prompt,
            system_instruction=system_instruction,
            model=model,
            temperature=temperature,
            max_tokens=max_tokens
        )
        return text

    @classmethod
    def synthesize_grounded_answer(cls, prompt: str, system_instruction: str) -> str:
        """
        Synthesizes a clean, natural, ChatGPT-style response directly answering the user's question,
        strictly grounded in the verified knowledge context.
        """
        if not system_instruction or "Verified Knowledge Context:" not in system_instruction:
            return f"Regarding your inquiry about '{prompt}', our team is available to assist."

        context_body = system_instruction.split("Verified Knowledge Context:")[1].strip()
        raw_sources = context_body.split("Source (")

        # 1. Parse knowledge sources and clean sentences
        clean_passages = []
        doc_titles = []
        for raw in raw_sources:
            if not raw.strip():
                continue
            title = "Verified Documentation"
            body = raw
            split_parts = re.split(r'\):\s*', raw, maxsplit=1)
            if len(split_parts) == 2:
                title = split_parts[0].strip()
                body = split_parts[1]
                doc_titles.append(title)

            # Clean markup artifacts, URLs, and page markers
            body_clean = re.sub(r'Page URL:\s*https?://\S+', '', body, flags=re.I)
            body_clean = re.sub(r'https?://\S+', '', body_clean)
            body_clean = re.sub(r'##\s*Page\s*\d+', '', body_clean, flags=re.I)
            clean_passages.append({"title": title, "body": body_clean.strip()})

        if not clean_passages:
            return f"I don't have enough verified information in our company knowledge base to answer that. I can connect you with our team if you'd like!"

        combined_context = "\n\n".join([p["body"] for p in clean_passages])

        # 0. Check for explicit FAQ entry match
        for p in clean_passages:
            faq_pattern = r'(?:Question|Q):\s*(.+?)\s*(?:Answer|A):\s*([\s\S]+?)(?=(?:\n(?:Question|Q):|$))'
            for match in re.finditer(faq_pattern, p["body"], re.IGNORECASE):
                fq, fa = match.group(1).strip(), match.group(2).strip()
                # Check overlap between user prompt and FAQ question
                p_terms = set(re.findall(r'\w+', prompt.lower()))
                fq_terms = set(re.findall(r'\w+', fq.lower()))
                if len(p_terms.intersection(fq_terms)) >= max(1, len(p_terms) * 0.5):
                    return fa

        # 2. Extract individual factual sentences from all context
        raw_sentences = []
        for p in clean_passages:
            # Handle bullet points
            lines = [l.strip() for l in p["body"].split("\n") if l.strip()]
            for line in lines:
                # Remove boilerplate headers & metadata tags
                if (
                    line.startswith("#") or 
                    line.lower().startswith("table of contents") or
                    re.match(r'^(document title|document id|classification|effective date|version|review cycle|document owner|page url):', line, re.I)
                ):
                    continue
                # Split multi-sentence lines
                s_list = re.split(r'(?<=[.?!])\s+', line)
                for s in s_list:
                    s_clean = s.strip().lstrip("-*•□ \t0123456789.)")
                    if (
                        len(s_clean) > 8 and 
                        not re.match(r'^(document title|document id|classification|effective date|version|review cycle|document owner|page url):', s_clean, re.I)
                    ):
                        raw_sentences.append(s_clean)

        if not raw_sentences:
            return "I don't have enough verified information in our company knowledge base to answer that."

        q_clean = prompt.strip()
        q_lower = q_clean.lower()
        stop_words = {
            "what", "is", "the", "a", "an", "in", "on", "at", "for", "to", "of", "and", "or",
            "are", "how", "do", "does", "did", "can", "could", "would", "should", "will", "tell", "me",
            "about", "our", "your", "you", "know", "this", "that", "these", "those", "explain", "please",
            "who", "where", "when", "why", "which", "have", "has", "had", "think", "with", "from",
            "give", "information", "info", "details", "detail", "overview", "summary", "provide", "show", "list", "help"
        }

        q_tokens = re.findall(r'\b[a-zA-Z0-9_-]+\b', q_lower)
        meaningful_tokens = [t for t in q_tokens if t not in stop_words and len(t) > 1] or q_tokens

        def stem(w: str) -> str:
            w = w.lower()
            for suffix in ["ing", "ments", "ment", "tions", "tion", "ed", "es", "s"]:
                if w.endswith(suffix) and len(w) - len(suffix) >= 3:
                    return w[:-len(suffix)]
            return w

        stemmed_q_tokens = [stem(t) for t in meaningful_tokens]

        # 3. Classify Question Intent
        is_what_do_you_do = any(re.search(pat, q_lower) for pat in [
            r'what does (your|the|this) company do',
            r'what (do|does) (you|the company|your company|this company) do',
            r'what is (your|the) company',
            r'what services (do you|does the company|are) provide',
            r'what are your services',
            r'what is your product',
            r'tell me about (your company|the company|yourself)',
            r'who are you and what do you do'
        ])

        is_boolean_question = any(q_lower.startswith(w) for w in [
            "can i", "can we", "can customers", "can users", "can you",
            "is there", "are there", "is it", "are you", "do you", "does the", "does your", "do they",
            "will you", "is support", "are refunds"
        ])

        is_refund_duration = any(k in q_lower for k in ["refund", "return", "money back"]) and any(k in q_lower for k in ["how long", "days", "timeline", "time limit", "window", "when", "period", "policy"])
        is_who_question = q_lower.startswith("who is") or q_lower.startswith("who are") or "founder" in q_lower or "ceo" in q_lower or "leadership" in q_lower
        is_hours_or_time_support = any(k in q_lower for k in ["night", "weekend", "24/7", "24*7", "hours", "available", "schedule", "timing", "time"]) and any(k in q_lower for k in ["support", "help", "service", "customer service"])

        # 4. Sentence Scoring against Query
        scored_sentences = []
        for sent in raw_sentences:
            s_lower = sent.lower()
            s_tokens = re.findall(r'\b[a-zA-Z0-9_-]+\b', s_lower)
            s_stems = [stem(t) for t in s_tokens]

            match_count = sum(1 for st in stemmed_q_tokens if st in s_stems or any(st in target for target in s_stems if len(st) >= 4))

            # Phrase bonus
            phrase_bonus = 0.0
            if any(token in s_lower for token in meaningful_tokens):
                phrase_bonus += 0.2

            # Specific intent boosts
            if is_what_do_you_do and any(w in s_lower for w in ["provides", "provide", "offers", "specializes in", "services", "cloud", "platform", "solution", "workforce"]):
                phrase_bonus += 0.8
            if is_hours_or_time_support and any(w in s_lower for w in ["24/7", "24*7", "support", "customer support", "round-the-clock", "night", "day"]):
                phrase_bonus += 0.9
            if is_refund_duration and any(w in s_lower for w in ["refund", "refunds", "30 days", "14 days", "return", "money-back", "guarantee"]):
                phrase_bonus += 0.9
            if is_who_question and any(w in s_lower for w in ["ceo", "founder", "founded by", "president", "director", "lead", "officer"]):
                phrase_bonus += 0.9

            total_score = match_count + phrase_bonus
            scored_sentences.append((total_score, sent))

        scored_sentences.sort(key=lambda x: x[0], reverse=True)

        # 5. Formulate Question-Specific Response

        # Case A: "What does your company do?" / Company Overview
        if is_what_do_you_do:
            for score, sent in scored_sentences:
                s_lower = sent.lower()
                if any(w in s_lower for w in ["provides", "provide", "offers", "offer", "specializes", "services", "cloud", "platform", "solutions"]):
                    # Transform cleanly to conversational answer
                    clean_ans = sent.strip().rstrip('.')
                    if clean_ans.lower().startswith("our company"):
                        return f"The company {clean_ans[11:].strip()}."
                    elif clean_ans.lower().startswith("we provide"):
                        return f"The company provides {clean_ans[10:].strip()}."
                    elif clean_ans.lower().startswith("we offer"):
                        return f"The company offers {clean_ans[8:].strip()}."
                    else:
                        return f"{clean_ans}."
            if scored_sentences and scored_sentences[0][0] > 0.5:
                return f"{scored_sentences[0][1].strip()}."

        # Case B: Support at Night / 24/7 Hours ("Can I get support at night?", "Is support 24/7?")
        if is_hours_or_time_support:
            for score, sent in scored_sentences:
                s_lower = sent.lower()
                if "24/7" in s_lower or "round-the-clock" in s_lower or "24 hours" in s_lower:
                    if "night" in q_lower or "weekend" in q_lower or "anytime" in q_lower or "can i" in q_lower:
                        return "Yes. The company provides 24/7 customer support, so assistance is available at night."
                    return f"Yes. {sent.strip()}."
                elif "support" in s_lower:
                    return f"{sent.strip()}."

        # Case C: Refund Window / Policy ("How long do I have to ask for a refund?", "Can I request refunds?")
        if is_refund_duration:
            for score, sent in scored_sentences:
                s_lower = sent.lower()
                if any(w in s_lower for w in ["refund", "return", "days", "money back"]):
                    clean_ans = sent.strip()
                    if is_boolean_question and not clean_ans.lower().startswith("yes"):
                        return f"Yes. {clean_ans}"
                    return clean_ans

        # Case D: Specific Entity / Person Query ("Who is the CEO?", "Who is the founder?")
        if is_who_question:
            has_person_info = any(score > 1.0 and any(w in sent.lower() for w in ["ceo", "founder", "founded by", "president", "director"]) for score, sent in scored_sentences)
            if not has_person_info:
                target_role = "the CEO" if "ceo" in q_lower else ("the founder" if "founder" in q_lower else "leadership")
                return f"I don't have information about {target_role} in our verified knowledge base."

        # Case E: Boolean / Yes-No / Capability Question
        if is_boolean_question:
            top_score, top_sent = scored_sentences[0] if scored_sentences else (0, "")
            if top_score >= 1.0:
                s_lower = top_sent.lower()
                # Check if sentence positively confirms the query concept
                if not s_lower.startswith("yes") and not s_lower.startswith("no"):
                    return f"Yes. {top_sent.strip()}"
                return top_sent.strip()

        # Case F: Specific multi-sentence or topic match
        if scored_sentences and scored_sentences[0][0] >= 0.8:
            selected_sents = []
            seen = set()
            for score, s in scored_sentences:
                if score < 0.5 or len(selected_sents) >= 3:
                    break
                s_key = s.lower().strip()
                if s_key not in seen:
                    seen.add(s_key)
                    selected_sents.append(s)

            return "\n\n".join(selected_sents)

        # Fallback Grounded Statement
        return "I don't have enough verified information in our company knowledge base to answer that specific question. I can connect you with our team if you'd like!"

    @classmethod
    async def stream_chat_completion(
        cls,
        messages: List[Dict[str, str]],
        system_instruction: str,
        model: Optional[str] = None,
        temperature: float = 0.3
    ) -> AsyncGenerator[str, None]:
        """
        Asynchronously streams LLM token events for low TTFT (Time-To-First-Token).
        Parses upstream OpenAI/Sarvam SSE protocol and yields clean text token deltas.
        """
        target_model = model or settings.DEFAULT_LLM_MODEL
        custom_url = settings.CUSTOM_LLM_API_URL

        if custom_url and settings.CUSTOM_LLM_API_KEY:
            try:
                headers = {"Content-Type": "application/json"}
                headers["Authorization"] = f"Bearer {settings.CUSTOM_LLM_API_KEY}"
                headers["api-subscription-key"] = settings.CUSTOM_LLM_API_KEY

                payload = {
                    "model": target_model,
                    "messages": [
                        {"role": "system", "content": system_instruction},
                        *messages
                    ],
                    "temperature": temperature,
                    "stream": True
                }

                async with httpx.AsyncClient(timeout=30.0) as client:
                    async with client.stream("POST", custom_url, headers=headers, json=payload) as response:
                        if response.status_code == 200:
                            buffer = ""
                            async for chunk in response.aiter_text():
                                buffer += chunk
                                while "\n" in buffer:
                                    line, buffer = buffer.split("\n", 1)
                                    line = line.strip()
                                    if not line or not line.startswith("data:"):
                                        continue
                                    data_str = line[5:].strip()
                                    if data_str == "[DONE]":
                                        return
                                    try:
                                        chunk_json = json.loads(data_str)
                                        choices = chunk_json.get("choices", [])
                                        if choices:
                                            delta = choices[0].get("delta", {})
                                            token_content = delta.get("content", "")
                                            if token_content:
                                                yield token_content
                                    except Exception:
                                        # Skip non-JSON or partial heartbeat SSE frames
                                        pass
                            return
                        else:
                            logger.error(f"[LLM Stream Error] Upstream {custom_url} returned HTTP {response.status_code}")
            except Exception as e:
                logger.error(f"[LLM Stream Exception] Stream error: {type(e).__name__} - {e}")

        # Fallback local stream with grounded synthesis
        last_message = messages[-1]["content"] if messages else "Hello"
        synthesized_text = cls.synthesize_grounded_answer(last_message, system_instruction)
        words = synthesized_text.split(" ")

        for i, word in enumerate(words):
            yield word + (" " if i < len(words) - 1 else "")
            await asyncio.sleep(0.015)
